#on:
#  push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./
        with:
          dest-owner: djn24
          dest-repo: DotNetLib
          package-path: '*.md'
          source-token: XXXXX
          repository-dispatch-token: XXXXX
